### PR TITLE
Add tests for spherical geometry

### PR DESCRIPTION
**Pull request by lhy11009**
There is a small issue in the function in the file

    source/world_builder/utilities.cc

where the variable c2 should be used instead of c1.

Other than that, I am adding a test for spherical geometry, but the result seems questionable. I am still figuring out the issue. Do you have an idea?

The test is set up in a similar way to the cartesian geometry, except that the longitude and latitudes are entered. I am only testing the result from one check point at this time, and the spreading rate and distance are calculated:

test_spherical_1

First, am I entering the coordinates in the right order? I thought it was (radius, longitude, and latitude) in spherical geometry.

The result is mentioned in the file

/tests/unit_tests/approval_tests/approved/unit_test_world_builder.WorldBuilder_Utilities_function__calculate_ridge_distance_and_spreading_spherical.txt

[0] = 6.33762e-08
[1] = 2.22412e+06
[2] = 0
[3] = 0

The first value is the spreading rate and the second is distance. 

In terms of the algorithm, I suspect the following lines still work for the spherical geometry, as the entries are angles.
What do you think?
`            const Point<2> v = segment_point1 - segment_point0;
            const Point<2> w1 = check_point - segment_point0;
            const Point<2> w2 = other_check_point - segment_point0;

            const double c1 = (w1[0] * v[0] + w1[1] * v[1]);
            const double c = (v[0] * v[0] + v[1] * v[1]);
            const double c2 = (w2[0] * v[0] + w2[1] * v[1]);
`

### CODE REVIEW

**Comment by danieldouglas92** [comment]
The other day I also saw the c2 error in the utilities file and that this was a mistake so thanks for catching and changing that also. In the .dat test files for spherical the coordinates input as (R, LON, LAT) so yes I think you're definitely inputting the coordinates right.

I'm confident that the code works for spherical coordinates because this is what Menno already had before I made this function, the temperatures look smooth and correct in spherical with this method so I think it is valid for both cartesian and spherical geometries. I think it's ok as long as the points lie on the surface because then as you said it's just angles.

`
        const double c1 = (w1[0] * v[0] + w1[1] * v[1]);
        const double c = (v[0] * v[0] + v[1] * v[1]);
        const double c2 = (w2[0] * v[0] + w2[1] * v[1]);
`

**Comment by danieldouglas92** [comment]
@lhy11009 the value for the spreading velocity output by the test isn't what I expected it to be actually. I agree with what you wrote in the figure that the velocity should be 1.5 cm/yr, but converting the value from the test into cm/yr gives 2.0 cm/yr.

**Comment by lhy11009** [comment]
Thanks for the reply. It's good to know the function should work. Let me figure out what the test is missing.

Is it possible that the coordinates are (Radius, LAT, LON) instead of (Radius, LON, LAT)? I got this from the code myself but now I am a little confused.

**Comment by danieldouglas92** [comment]
@lhy11009 It might be because the query point is closer to the point on the other ridge? The distance to `p1a` is 2418km, the distance to `p1b` is 2475 km, and the distance to `p2a` is 2222km

**Comment by danieldouglas92** [comment]
https://github.com/GeodynamicWorldBuilder/WorldBuilder/issues/201 this is the issue confirming that the convention is LON, LAT

**Comment by lhy11009** [comment]
Thanks for reaffirming this.

Actually, the bug arises because the spherical coordinates needs to be first converted to cartesian and then to the natural coordinate, but the function of

`Objects::NaturalCoordinate()`

doesn't see that.

**Comment by lhy11009** [comment]
Okay, I add a few points and fix the tests. This is ready to be merged to your branch.

**Comment by lhy11009** [comment]
Okay, it seems the indentation test doesn't pass. However, I do make indent before I commit.

**Pull request merged**
