### PR TITLE
Fix ridge distance function

### PR DESCRIPTION
**Pull request by lhy11009**
Hi Daniel, I think we first need to fix the implementation and tests of the function calculate_ridge_distance_and_spreading but we move further with calculate_effective_trench_and_plate_ages

This PR adds one unit test and fixes one issue in the function calculate_ridge_distance_and_spreading

Below is a description of the test:
The test creates a ridge with two parts connected by a transform fault and calls the function on 4 query points.
The issue exists with the 4th point (100, 76), it should have the spreading rate intermediate (3.5 m/yr) of the two points above (4 m /yr) and below (3 m/yr).
With the previous implementation, it would have the spreading rate of (4 m / yr), because the spreading rate calculated for each segment is not parsed to the final result.

pr_01
the 4th point: (100, 76), not (100, 51).

Now, there seems to be a lingering issue with the 2nd test point. This point is outside of the ridge, but the functions return a result nonetheless.

### CODE REVIEW

**Comment by lhy11009** [comment]
@danieldouglas92, maybe it's also easier to arrange a short meeting for this one.
My available time on Mon, eastern time: 11 am - 13 pm.  14 pm - 15 pm, 16 - 18 pm.
Tue, 11 am - 15 pm.

**Comment by danieldouglas92** [comment]
Thanks for working on this, a meeting would be great because I think I understand the problem you're outlining but it would be good to go over it together. 11am EST works for me!

**Comment by lhy11009** [comment]
okay, we'll meet Monday 11 am. Here is the zoom link:

Haoyuan Li is inviting you to a scheduled Zoom meeting.

Topic: Haoyuan Li's Personal Meeting Room

Join Zoom Meeting
https://ucdavis.zoom.us/j/7989138001

**Comment by danieldouglas92** [comment]
@lhy11009 I think I realized what is happening with those tests. I think the output is actually right! Query Point 1 is at {1e3, 0}, but the ridge is defined as the segment from {{200e3, -1e3}, {200e3, 50e3}}.  Therefore Query Point 1 is in between the ridge, not lying right on the edge, and the value of the velocity here SHOULD be higher because it's linearly interpolating from 1 to 2. Query Point 2 is at {1e3, -2e3}, and so it should have a spreading velocity equal to the spreading velocity defined at the end of the ridge segment at {200e3, -1e3}. You've set the spreading velocity to be 1 there, so when converting to SI units the velocity should be `3.16881-08`, which is indeed what the test says the velocity is.

**Pull request merged**
